version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: fullcycle-nest-bank
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: fullcycle-nest-bank-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
    ports:
      - 15432:5432
